apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-playground
  namespace: argocd
  annotations:
    argocd.argoproj.io/refresh: "normal"
spec:
  project: default
  source:
    repoURL: https://github.com/ZenabaNouriatte/IoT_zmogne
    targetRevision: HEAD
    path: p3/confs
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true